# Generated by Django 3.2.9 on 2021-12-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(verbose_name='Полное имя исполнителя')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID заявки')),
                ('task_name', models.TextField(verbose_name='Название заявки')),
                ('task_status', models.TextField(verbose_name='Статус заявки')),
                ('task_creator_name', models.TextField(verbose_name='Заявитель')),
                ('task_changed', models.TextField(verbose_name='Изменена')),
                ('task_executor',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser.taskexecutor',
                                   verbose_name='Исполнитель заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
