# Generated by Django 3.2.9 on 2021-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_parse_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время парсинга'),
        ),
    ]
