# Generated by Django 3.2.9 on 2021-12-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_task_task_parse_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.TextField(default='Не указан', verbose_name='Категория заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_executor',
            field=models.TextField(verbose_name='Исполнитель заявки'),
        ),
    ]
