# Generated by Django 3.2.9 on 2021-12-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('parser', '0003_auto_20211204_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser.taskexecutor',
                                    verbose_name='Исполнитель заявки'),
        ),
        migrations.CreateModel(
            name='ExecutorsAndTasksId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser.taskexecutor',
                                                  verbose_name='Исполнитель')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser.task',
                                              verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заявка и её исполнитель',
                'verbose_name_plural': 'Заявки и их исполнители',
            },
        ),
    ]
