# Generated by Django 3.2.9 on 2021-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_remove_task_task_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(default=' ', verbose_name='Описание'),
        ),
    ]
