# Generated by Django 3.2.9 on 2021-12-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_task_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
    ]
