# Generated by Django 3.2.9 on 2021-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_usersubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
    ]
