# Generated by Django 3.2.9 on 2021-12-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_remove_task_task_executor'),
        ('bot', '0003_profile_is_registered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Полученное сообщение', 'verbose_name_plural': 'Полученные сообщения'},
        ),
        migrations.CreateModel(
            name='SendedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено в тг')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', verbose_name='Профиль')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser.task', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Отправленная заявка',
                'verbose_name_plural': 'Отправленные заявки',
            },
        ),
    ]
