# Generated by Django 3.2.9 on 2021-12-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_remove_task_task_executor'),
        ('bot', '0004_auto_20211205_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendedTask',
            new_name='SentTask',
        ),
    ]
